[toolchain]
anchor_version = "0.29.0"

[features]
seeds = false
skip-lint = false

[programs.localnet]
oft = "rU4eMA4wSoXLUodsLJWTJyQhAhdYps5rf4SRwpT7nHa"
solana_proxy = "2mk17sMDoTrxWKYm2hCVpD4pQcbSG2mnQdQzfdHVTKey"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/dmitry/.config/solana/id.json"

[scripts]
test = "npx jest test/anchor"
