[toolchain]
anchor_version = "0.29.0"

[features]
seeds = false
skip-lint = false

[programs.localnet]
solana_proxy = "7X5WKxXLPy9TbJDFejq288HezLmWayZWudKMmUC2d9rB"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/Users/zion/.config/solana/id.json"

[scripts]
test = "npx jest test/anchor"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[[test.genesis]]
address = "76y77prsiCMvXMjuoZ5VRrhG5qYBrUMYTE5WgHqgjEn6"
program = "test/anchor/bin/endpoint.so"

[[test.genesis]]
address = "279tDX6wTFgrJaRnGEdjik3NLR8B9AKY1pKVFYcxvw7c"
program = "test/anchor/bin/uln.so"

[test.validator]
bind_address = "127.0.0.1"
url = "https://api.devnet.solana.com"
ledger = ".anchor/test-ledger"
rpc_port = 8899
